### ISSUE TITLE
need more data from get_portfolio()

### ISSUE THREAD

**Issue by seralekseenko** [GeminiAgentsToolkit/investor-agent#30]
Need simple data set for each position:

| Ticker           | qty | entry price | cost basics | current price (market) | market value | Profit/loos |
|------------------|-------|-----------------|-----------------|----------------------------------|---------------------|----------------|
| AMD    | 10       | 140    | 1400       | 150   | 1500       | +100 |
| PLUG260116C00005000  | 1     | 0.59   | 59 | 0.45  | 45  | -14 |

It is only example. JSON format will be goood :)

There is the sub-task: #40

**Comment by b0noI** [comment]
done, ask something like: show me full portfolio with all the details
