### ISSUE TITLE
Fix source of truth of the VERSION.

### ISSUE THREAD

**Issue by seralekseenko** [GeminiAgentsToolkit/investor-agent#59]
1. The problem is in the `telegram_bot.py` → there is the hard-code value of VERSION 
![image](https://github.com/user-attachments/assets/6beb22ea-0f14-492f-a620-3531cf653a43)

2. The `deploy_prod.sh` increments the VERSION based on what? Just on previous number? Okay, my previous number in VERSION file is `3`. But in the code it is `7` and in GitHub it is `8`. Where is truth?
3. When I do test runs of `deploy_prod.sh` during development, I get an uncontrolled increment of the VERSION number. I saw it when the version reached number 15))))

Why do we need this VERSION at all?
I think this is necessary both for testing and for better orientation when using the bot in direct work.

**Comment by b0noI** [comment]
VERSION is needed to confirm exactly which bot you are talking to, none of specified problems are relevant if you are the only person deploying it. version file should be in .gitignore, removed from the GitHub and only exists in your machine from where you will be deploying it.

Can it be done better? 100% it can :)

**Comment by seralekseenko** [comment]
For some reason I forgot to write my proposal.  )) Here's my suggestion: a bot version can be generated each time based on a branch + commit.

**Comment by seralekseenko** [comment]
It is forbidden to create a version from uncommitted files. We work only on Git!
